# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42fc8c618b8a6e54a63676f91ed1340e51e367586ed53798cb9d6ced0110c746c5037ca7dd7f5a7914096e06e566dcb0e7ffa658b4f8a94ab9998e0772f4a315

test:
  secret_key_base: 8fefd71bd228bb4bc9bf32b6effc1e7f693bed338016d4c257ff4427d8c5b2b8cbad889224c004dec18b4ac50ed273f2a5f47e406015580fceb08cb8515279fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
